# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mapram.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(322, 274)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 20, 151, 18))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit_minOdl = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_minOdl.setGeometry(QtCore.QRect(170, 10, 91, 32))
        self.lineEdit_minOdl.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_minOdl.setObjectName("lineEdit_minOdl")
        self.lineEdit_skala = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_skala.setGeometry(QtCore.QRect(140, 50, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_skala.setFont(font)
        self.lineEdit_skala.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_skala.setObjectName("lineEdit_skala")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 57, 18))
        self.label_2.setObjectName("label_2")
        self.ok = QtWidgets.QPushButton(Dialog)
        self.ok.setGeometry(QtCore.QRect(10, 230, 191, 34))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.ok.setFont(font)
        self.ok.setObjectName("ok")
        self.pushButton_porzuc = QtWidgets.QPushButton(Dialog)
        self.pushButton_porzuc.setGeometry(QtCore.QRect(210, 230, 88, 34))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.pushButton_porzuc.setFont(font)
        self.pushButton_porzuc.setObjectName("pushButton_porzuc")
        self.radioButton_przeg = QtWidgets.QRadioButton(Dialog)
        self.radioButton_przeg.setGeometry(QtCore.QRect(50, 160, 151, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.radioButton_przeg.setFont(font)
        self.radioButton_przeg.setChecked(True)
        self.radioButton_przeg.setObjectName("radioButton_przeg")
        self.radioButton_inna = QtWidgets.QRadioButton(Dialog)
        self.radioButton_inna.setGeometry(QtCore.QRect(50, 190, 251, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.radioButton_inna.setFont(font)
        self.radioButton_inna.setObjectName("radioButton_inna")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(270, 20, 31, 20))
        self.label_3.setObjectName("label_3")
        self.pushButton_2k = QtWidgets.QPushButton(Dialog)
        self.pushButton_2k.setGeometry(QtCore.QRect(0, 100, 31, 34))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.pushButton_2k.setFont(font)
        self.pushButton_2k.setObjectName("pushButton_2k")
        self.pushButton_5k = QtWidgets.QPushButton(Dialog)
        self.pushButton_5k.setGeometry(QtCore.QRect(40, 100, 31, 34))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.pushButton_5k.setFont(font)
        self.pushButton_5k.setObjectName("pushButton_5k")
        self.pushButton_50k = QtWidgets.QPushButton(Dialog)
        self.pushButton_50k.setGeometry(QtCore.QRect(280, 100, 41, 34))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.pushButton_50k.setFont(font)
        self.pushButton_50k.setObjectName("pushButton_50k")
        self.pushButton_10k = QtWidgets.QPushButton(Dialog)
        self.pushButton_10k.setGeometry(QtCore.QRect(80, 100, 41, 34))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.pushButton_10k.setFont(font)
        self.pushButton_10k.setObjectName("pushButton_10k")
        self.pushButton_25k = QtWidgets.QPushButton(Dialog)
        self.pushButton_25k.setGeometry(QtCore.QRect(180, 100, 41, 34))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.pushButton_25k.setFont(font)
        self.pushButton_25k.setObjectName("pushButton_25k")
        self.pushButton_20k = QtWidgets.QPushButton(Dialog)
        self.pushButton_20k.setGeometry(QtCore.QRect(130, 100, 41, 34))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.pushButton_20k.setFont(font)
        self.pushButton_20k.setObjectName("pushButton_20k")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(0, 140, 321, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton_30k = QtWidgets.QPushButton(Dialog)
        self.pushButton_30k.setGeometry(QtCore.QRect(230, 100, 41, 34))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.pushButton_30k.setFont(font)
        self.pushButton_30k.setObjectName("pushButton_30k")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dane do MapRam-a"))
        self.label.setText(_translate("Dialog", "Minimalne odległości:"))
        self.lineEdit_minOdl.setText(_translate("Dialog", "600"))
        self.lineEdit_skala.setText(_translate("Dialog", "5000"))
        self.label_2.setText(_translate("Dialog", "Skala:"))
        self.ok.setText(_translate("Dialog", "OK"))
        self.pushButton_porzuc.setText(_translate("Dialog", "Porzuć"))
        self.radioButton_przeg.setText(_translate("Dialog", "mapa przeglądowa"))
        self.radioButton_inna.setText(_translate("Dialog", "mapa PPOŻ, FOCHR, OGÓLNA"))
        self.label_3.setText(_translate("Dialog", "m"))
        self.pushButton_2k.setText(_translate("Dialog", "2k"))
        self.pushButton_5k.setText(_translate("Dialog", "5k"))
        self.pushButton_50k.setText(_translate("Dialog", "50k"))
        self.pushButton_10k.setText(_translate("Dialog", "10k"))
        self.pushButton_25k.setText(_translate("Dialog", "25k"))
        self.pushButton_20k.setText(_translate("Dialog", "20k"))
        self.pushButton_30k.setText(_translate("Dialog", "30k"))


