# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Lch
                                 A QGIS plugin
 Plugin ułatwiający generowanie map dla UPUL
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-04-05
        copyright            : (C) 2019 by LAS-R
        email                : biuro@las-r.pl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Lch class from file Lch.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .lch import Lch
    return Lch(iface)
