# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Lch
                                 A QGIS plugin
 Plugin ułatwiający generowanie map dla UPUL
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2019-04-05
        git sha              : $Format:%H$
        copyright            : (C) 2024 by LAS-R
        email                : biuro@las-r.pl
        autor                : Paweł Krąpiec
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from PyQt5.QtCore import QSettings, QTranslator, qVersion, QCoreApplication
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QAction, QMenu

# Initialize Qt resources from file resources.py
# from .resources import *
# Import the code for the dialog
import os.path

from .skrypty import genMapRam, ustaw_mape, ustawMapRam, pomocnicze, \
    planarize, dane_przetwarzanie, dopisz_kody, kasowniki, generuj_etykiety, \
    ustaw_mapy_katalog, eksportuj_mapy_katalog, spisy_atlas, \
    shp_generuj_sulmn, uzupelnij_meta, struktura, generuj_krzewy, \
    shp_sulmn_spr, shp_przygotuj_klu_lft, drukuj_mapy_katalog



class Lch:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'Lch_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)

            if qVersion() > '4.3.3':
                QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.akcje_toolbara = []
        self.toolbar = self.iface.addToolBar('LCH')
        self.toolbar.setObjectName('LCH')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('Lch', message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None
    ):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        # will be set False in run()
        self.first_start = True
        self.akcje_toolbara = []

        self.menu = QMenu(self.iface.mainWindow())
        self.menu.setObjectName('LCH')
        self.menu.setTitle('LCH')

        menuBar = self.iface.mainWindow().menuBar()
        menuBar.insertMenu(self.iface.firstRightStandardMenu().menuAction(),
                           self.menu)

        # AKCJE -------------
        self.a_struk = QAction(
            QIcon(os.path.join(self.plugin_dir, 'ico', 'struk.png')),
            'Generuj strukturę map',
            self.iface.mainWindow())
        self.a_struk.triggered.connect(self.generuj_strukture)

        self.a_mapram = QAction(
            QIcon(os.path.join(self.plugin_dir, 'ico', 'genMapRam.png')),
            'Generuj MapRam',
            self.iface.mainWindow())
        self.a_mapram.triggered.connect(self.generuj_mapram)

        self.a_szer900 = QAction(
            QIcon(os.path.join(self.plugin_dir, 'ico', 'szer900.png')),
            'Ustaw szer mapy na 90cm',
            self.iface.mainWindow())
        self.a_szer900.triggered.connect(self.ustaw_szer900)

        self.a_dodaj_wyn = QAction(
            QIcon(os.path.join(self.plugin_dir, 'ico', 'dodajRec.png')),
            'Dodaj wyniesienie',
            self.iface.mainWindow())
        self.a_dodaj_wyn.triggered.connect(self.dodaj_wyniesienie)

        self.a_dopisz_xy = QAction(
            QIcon(os.path.join(self.plugin_dir, 'ico', 'dopiszXY.png')),
            'Dopisz wsp wierzchołka',
            self.iface.mainWindow())
        self.a_dopisz_xy.triggered.connect(self.dopisz_xy)

        self.a_wys900 = QAction(
            QIcon(os.path.join(self.plugin_dir, 'ico', 'wys900.png')),
            'Ustaw wys mapy na 90cm',
            self.iface.mainWindow())
        self.a_wys900.triggered.connect(self.ustaw_wys900)

        self.a_szerA3 = QAction(
            QIcon(os.path.join(self.plugin_dir, 'ico', 'szerA3.png')),
            'Ustaw szer mapy na A3',
            self.iface.mainWindow())
        self.a_szerA3.triggered.connect(self.ustaw_szerA3)

        self.a_wysA3 = QAction(
            QIcon(os.path.join(self.plugin_dir, 'ico', 'wysA3.png')),
            'Ustaw wys mapy na A3',
            self.iface.mainWindow())
        self.a_wysA3.triggered.connect(self.ustaw_wysA3)

        self.a_szer = QAction(
            QIcon(os.path.join(self.plugin_dir, 'ico', 'szer.png')),
            'Ustaw szer mapy na podana',
            self.iface.mainWindow())
        self.a_szer.triggered.connect(self.ustaw_szer)

        self.a_wys = QAction(
            QIcon(os.path.join(self.plugin_dir, 'ico', 'wys.png')),
            'Ustaw wys mapy na podana',
            self.iface.mainWindow())
        self.a_wys.triggered.connect(self.ustaw_wys)

        self.a_ustaw_mape = QAction(
            QIcon(os.path.join(self.plugin_dir, 'ico', 'ustawMape.png')),
            'Ustaw Mapę',
            self.iface.mainWindow())
        self.a_ustaw_mape.triggered.connect(self.ustaw_mape)

        self.a_ustaw_leg = QAction(
            QIcon(os.path.join(self.plugin_dir, 'ico', 'ustawLeg.png')),
            'Ustaw Legendę',
            self.iface.mainWindow())
        self.a_ustaw_leg.triggered.connect(self.ustaw_legende)

        self.a_spisy_atl = QAction(
            QIcon(None), 'Generuj spisy atlasów', self.iface.mainWindow())
        self.a_spisy_atl.triggered.connect(self.generuj_spisy_atlasow)

        self.a_przygotuj_upul = QAction(
            QIcon(None), 'Pomocnicze dla UPUL', self.iface.mainWindow())
        self.a_przygotuj_upul.triggered.connect(self.generuj_pomocnicze_upul)

        self.a_przygotuj_ppoz = QAction(
            QIcon(None), 'Pomocnicze dla PPOŻ', self.iface.mainWindow())
        self.a_przygotuj_ppoz.triggered.connect(self.generuj_pomocnicze_ppoz)

        self.a_przygotuj_fochr = QAction(
            QIcon(None), 'Pomocnicze dla FOCHR', self.iface.mainWindow())
        self.a_przygotuj_fochr.triggered.connect(self.generuj_pomocnicze_fochr)

        self.a_podziel_obrebami = QAction(
            QIcon(None), 'Podziel obrębami', self.iface.mainWindow())
        self.a_podziel_obrebami.triggered.connect(self.dziel_obrebami)

        self.a_polacz_warstwy = QAction(
            QIcon(None), 'Połącz warstwy', self.iface.mainWindow())
        self.a_polacz_warstwy.triggered.connect(self.lacz_warstwy)

        self.a_planarize = QAction(
            QIcon(os.path.join(self.plugin_dir, 'ico', 'planarize.png')),
            'Planarize', self.iface.mainWindow())
        self.a_planarize.triggered.connect(self.planaryzuj)

        self.a_lin_oddz = QAction(
            QIcon(os.path.join(self.plugin_dir, 'ico', 'gen_lin_oddz.png')),
            'Linie oddziałowe', self.iface.mainWindow())
        self.a_lin_oddz.triggered.connect(self.generuj_lin_oddz)

        self.a_gen_klu_lft = QAction(
            QIcon(os.path.join(self.plugin_dir, 'ico', 'gen_klu_lft.png')),
            'Generuj KLU_LFT', self.iface.mainWindow())
        self.a_gen_klu_lft.triggered.connect(self.generuj_klu_lft)

        self.a_dopisz_kody = QAction(
            QIcon(os.path.join(self.plugin_dir, 'ico', 'wydz_dopisz.png')),
            'Dopisz kody', self.iface.mainWindow())
        self.a_dopisz_kody.triggered.connect(self.dopisz_meta)

        self.a_gen_kas = QAction(
            QIcon(os.path.join(self.plugin_dir, 'ico', 'gen_kas.png')),
            'Generuj kasowniki', self.iface.mainWindow())
        self.a_gen_kas.triggered.connect(self.generuj_kasowniki)

        self.a_gen_etyk = QAction(
            QIcon(os.path.join(self.plugin_dir, 'ico', 'gen_etyk.png')),
            'Generuj  etykiety', self.iface.mainWindow())
        self.a_gen_etyk.triggered.connect(self.generuj_etykiety)

        self.a_ustaw_mapy = QAction(
            QIcon(None),
            'Ustaw Mapy (Katalog)', self.iface.mainWindow())
        self.a_ustaw_mapy.triggered.connect(self.ustaw_mapy_w_katalogu)

        self.a_ustaw_leg_k = QAction(
            QIcon(None),
            'Ustaw Legendy (Katalog)', self.iface.mainWindow())
        self.a_ustaw_leg_k.triggered.connect(self.ustaw_leg_w_katalogu)

        self.a_uakt_meta = QAction(
            QIcon(None),
            'Uaktualnij Metadane (Katalog)',
            self.iface.mainWindow())
        self.a_uakt_meta.triggered.connect(self.uaktualnij_mapy)

        self.a_eksportuj_mapy = QAction(
            QIcon(None),
            'Eksportuj Mapy (Katalog)', self.iface.mainWindow())
        self.a_eksportuj_mapy.triggered.connect(self.eksport_map_z_katalogu)

        self.a_drukuj_mapy = QAction(
            QIcon(None),
            'Drukuj Mapy (Katalog)', self.iface.mainWindow())
        self.a_drukuj_mapy.triggered.connect(self.drukuj_mapy_z_katalogu)

        self.a_gen_sulmn = QAction(
            QIcon(os.path.join(self.plugin_dir, 'ico', 'sulmn.png')),
            'Generuj SULMN',
            self.iface.mainWindow())
        self.a_gen_sulmn.triggered.connect(self.generuj_sulmn)

        self.a_spr_sulmn = QAction(
            QIcon(os.path.join(self.plugin_dir, 'ico', 'sulmn.png')),
            'Przygotuj sprawdzenie SULMNa',
            self.iface.mainWindow())
        self.a_spr_sulmn.triggered.connect(self.sprawdz_sulmn)

        self.a_gen_krzew = QAction(
            QIcon(os.path.join(self.plugin_dir, 'ico', 'krzew.png')),
            'Generuj powierzchnie krzewów',
            self.iface.mainWindow())
        self.a_gen_krzew.triggered.connect(self.generuj_krzewy)

        self.a_co_nowego = QAction(
            'Co nowego?',
            self.iface.mainWindow())
        self.a_co_nowego.triggered.connect(self.pokaz_co_nowego)

        # MENU -------------
        self.menu_pom = QMenu('Przygotuj Pomocnicze', self.menu)
        self.menu_pom.addAction(self.a_przygotuj_upul)
        self.menu_pom.addAction(self.a_przygotuj_ppoz)
        self.menu_pom.addAction(self.a_przygotuj_fochr)

        self.menu_narzedzia = QMenu('Narzędziowe', self.menu)
        self.menu_narzedzia.addAction(self.a_gen_klu_lft)
        self.menu_narzedzia.addAction(self.a_polacz_warstwy)
        self.menu_narzedzia.addAction(self.a_spisy_atl)
        self.menu_narzedzia.addAction(self.a_gen_krzew)

        self.menu_ustaw_pojedynczo = QMenu('Ustaw pojedynczo', self.menu)
        self.menu_ustaw_pojedynczo.addAction(self.a_ustaw_mape)
        self.menu_ustaw_pojedynczo.addAction(self.a_ustaw_leg)

        self.menu.addAction(self.a_struk)
        self.menu.addAction(self.a_dopisz_kody)
        self.menu.addAction(self.a_gen_kas)
        self.menu.addAction(self.a_lin_oddz)
        self.menu.addAction(self.a_gen_etyk)
        self.menu.addAction(self.a_mapram)
        self.menu.addMenu(self.menu_pom)
        self.menu.addAction(self.a_podziel_obrebami)
        self.menu.addSeparator()
        self.menu.addAction(self.a_ustaw_mapy)
        self.menu.addAction(self.a_ustaw_leg_k)
        self.menu.addMenu(self.menu_ustaw_pojedynczo)
        self.menu.addSeparator()
        self.menu.addAction(self.a_eksportuj_mapy)
        self.menu.addAction(self.a_drukuj_mapy)
        self.menu.addSeparator()
        self.menu.addAction(self.a_uakt_meta)
        self.menu.addSeparator()
        self.menu.addMenu(self.menu_narzedzia)
        self.menu.addSeparator()
        self.menu.addAction(self.a_gen_sulmn)
        self.menu.addAction(self.a_spr_sulmn)
        self.menu.addSeparator()
        self.menu.addAction(self.a_co_nowego)

        # TOOLBAR ----------
        self.toolbar.addAction(self.a_struk)
        self.toolbar.addSeparator()
        self.toolbar.addAction(self.a_dopisz_kody)
        self.toolbar.addAction(self.a_gen_kas)
        self.toolbar.addAction(self.a_lin_oddz)
        self.toolbar.addAction(self.a_gen_etyk)
        self.toolbar.addAction(self.a_dodaj_wyn)
        self.toolbar.addAction(self.a_mapram)
        self.toolbar.addSeparator()
        self.toolbar.addAction(self.a_dodaj_wyn)
        self.toolbar.addAction(self.a_dopisz_xy)
        self.toolbar.addAction(self.a_wys)
        self.toolbar.addAction(self.a_wysA3)
        self.toolbar.addAction(self.a_wys900)
        self.toolbar.addAction(self.a_szer)
        self.toolbar.addAction(self.a_szerA3)
        self.toolbar.addAction(self.a_szer900)
        # self.toolbar.addSeparator()
        # self.toolbar.addAction(self.a_planarize)

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""

        if self.menu is not None:
            self.iface.mainWindow().menuBar().removeAction(
                self.menu.menuAction())
        for a in self.akcje_toolbara:
            self.iface.removeToolBarIcon(a)
        del self.toolbar

    def generuj_mapram(self):
        m = genMapRam.GenerujMapRam(self.iface)
        m.wykonaj()

    def ustaw_mape(self):
        m = ustaw_mape.UstawMape(self.iface)
        if not m.sprawdz_warstwy():
            return
        if not m.znajdz_bazy():
            return
        m.pobierz_meta()
        m.zmien_meta_data()
        if not m.przesun_elem():
            return
        ustaw_mape.zapisz_z_przyrostkiem_ark(self.iface, m)

    def ustaw_legende(self):
        ustaw_mape.ustaw_leg(self.iface)

    def ustaw_szer(self):
        ustawMapRam.ustawSzer(self.iface, )

    def ustaw_szer900(self):
        ustawMapRam.ustawSzer(self.iface, '900')

    def ustaw_szerA3(self):
        ustawMapRam.ustawSzer(self.iface, 'A3')

    def ustaw_wys(self):
        ustawMapRam.ustawWys(self.iface, )

    def ustaw_wys900(self):
        ustawMapRam.ustawWys(self.iface, '900')

    def ustaw_wysA3(self):
        ustawMapRam.ustawWys(self.iface, 'A3')

    def dodaj_wyniesienie(self):
        ustawMapRam.dodajWyniesienie(self.iface)

    def dopisz_xy(self):
        ustawMapRam.dopiszXY(self.iface)

    def generuj_pomocnicze_upul(self):
        p = pomocnicze.WarstwyPomocnicze(self.iface)
        if p.znajdz_oddz():
            p.przygotuj_upul()

    def generuj_pomocnicze_ppoz(self):
        p = pomocnicze.WarstwyPomocnicze(self.iface)
        if p.znajdz_oddz():
            p.przygotuj_ppoz()
            p.wytnij_maske()

    def generuj_pomocnicze_fochr(self):
        p = pomocnicze.WarstwyPomocnicze(self.iface)
        if p.znajdz_oddz():
            p.przygotuj_fochr()
            p.wytnij_maske()

    def dziel_obrebami(self):
        dane_przetwarzanie.podziel_obrebami(self.iface)

    def lacz_warstwy(self):
        dane_przetwarzanie.polacz_warstwy(self.iface)

    def dopisz_lin_oddz(self):
        dane_przetwarzanie.UzupelnijLinPnsw(self.iface)

    def generuj_lin_oddz(self):
        dane_przetwarzanie.linie_oddz(self.iface)

    def generuj_klu_lft(self):
        shp_przygotuj_klu_lft.przygotuj_klu_lft(self.iface)

    def planaryzuj(self):
        planarize.Planarize(self.iface)

    def dopisz_meta(self):
        d = dopisz_kody.DopiszKody(self.iface)
        d.pobierz_dane()
        d.pobierzBaze()
        d.dopisz_kody()
        dane_przetwarzanie.UzupelnijLinPnsw(self.iface)

    def generuj_kasowniki(self):
        kasowniki.GenerujKasowniki(self.iface)

    def generuj_etykiety(self):
        e = generuj_etykiety.Etykietownik(self.iface)
        if e.znajdz_warstwy():
            e.generuj_pkt_wydz()
            e.generuj_pkt_dzewid()
            e.generuj_etykiety_wydz()
            e.generuj_etykiety_dzewid()
            e.dodaj_warstwy()

    def ustaw_mapy_w_katalogu(self):
        ustaw_mapy_katalog.ustaw_mapy(self.iface)

    def ustaw_leg_w_katalogu(self):
        ustaw_mapy_katalog.ustaw_leg(self.iface)

    def eksport_map_z_katalogu(self):
        eksportuj_mapy_katalog.eksportuj_mapy(self.iface)

    def drukuj_mapy_z_katalogu(self):
        drukuj_mapy_katalog.drukuj_mapy(self.iface)

    def generuj_spisy_atlasow(self):
        spisy_atlas.GenerujSpisAtlasow(self.iface)

    def generuj_sulmn(self):
        g = shp_generuj_sulmn.GenerujSulmn(self.iface)
        if g.wydz is False:
            return
        if g.sprawdzDane():
            g.pobierz()
            g.przygotujRobocze()
            g.generujWarstwy()

    def uaktualnij_mapy(self):
        uzupelnij_meta.uaktualnij_mapy(self.iface)

    def generuj_strukture(self):
        """Generuj strukture do wskazanej bazy danych"""
        struktura.stworz_drzewo(self.iface)

    def generuj_krzewy(self):
        """Generowanie powierzchni krzewów na podstawie odpowiedniej warstwy pkt"""
        gen = generuj_krzewy.wygeneruj_powierzchnie(self.iface)

    def sprawdz_sulmn(self):
        g = shp_sulmn_spr.GenerujSulmnSpr(self.iface)
        if g.wydz is False:
            return
        if g.sprawdzDane():
            g.pobierz()
            g.przygotujRobocze()
            g.generujWarstwy()

            g.przygotuj_projekt()

    def pokaz_co_nowego(self):
        from PyQt5.QtWidgets import QDialog, QVBoxLayout, QTextBrowser, QDialogButtonBox
        changelog_path = os.path.join(self.plugin_dir, 'CHANGELOG.txt')
        try:
            with open(changelog_path, encoding='utf-8') as f:
                tekst = f.read()
        except Exception:
            tekst = 'Nie udało się wczytać pliku CHANGELOG.txt'

        dlg = QDialog(self.iface.mainWindow())
        dlg.setWindowTitle('Co nowego?')
        dlg.setMinimumSize(640, 480)
        layout = QVBoxLayout()
        tb = QTextBrowser()
        tb.setPlainText(tekst)
        layout.addWidget(tb)
        btn = QDialogButtonBox(QDialogButtonBox.Close)
        btn.rejected.connect(dlg.reject)
        layout.addWidget(btn)
        dlg.setLayout(layout)
        dlg.exec_()
